nameOverride: "app"
fullnameOverride: "app"

securityContext: {}
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

service:
  type: NodePort
  port: 3000
  targetPort: 3000

nodeSelector: {}

replicaCount: 6

resources:
  limits:
    cpu: 40m
    memory: 128Mi
  requests:
    cpu: 40m
    memory: 128Mi

environment: develop

image:
  pullPolicy: IfNotPresent
  repository: ""
  tag: latest

autoPromotionEnabled: false
